import MyAppBar from "@src/components/common/MyAppBar";
import Head from "next/head";



export default function Blog() {

  return (
    <>
      <Head>
        <title>Blog | The movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar></MyAppBar>
      <div>
        Blog
      </div>
    </>
  );
}
