import MyAppBar from "@src/components/common/MyAppBar";
import Head from "next/head";

import { useEffect, useState } from "react"; 
import {ThemeProvider, useTheme } from "@mui/material";
import {  lighttheme,Darktheme } from "@src/styles/mui/theme"; 
import { CssBaseline } from "@mui/material";
import { useDispatch, useSelector } from "react-redux";
import { getActiveTheme, selectTheme } from "@src/redux/reducers/themeReducer";


export default function Blog() {

  const dispatch= useDispatch();
  const currentTheme = useSelector(selectTheme).activeTheme;

  useEffect(() => {
    dispatch(getActiveTheme()); // To get theme from Cookie
  }, []);

    const theme = useTheme();

//const[currentTheme,setCurrentTheme] = useState("dark");
  return (
    <>
    <ThemeProvider theme={currentTheme === "dark" ? Darktheme : lighttheme}>
      <CssBaseline/>
      <Head>
        <title>Blog | The movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppBar />
      <div>
        Blog
      </div>
      </ThemeProvider>
    </>
  );
}
