//Imports from react
import Head from "next/head";
import { useEffect, useState } from "react"; //state can change many states in page
import MyAppBar from "@src/components/common/MyAppBar";
import { Box, Button, ThemeProvider,Container, Grid } from "@mui/material";
import { CssBaseline } from "@mui/material";
import { lighttheme, Darktheme } from "@src/styles/mui/theme"; 

import {useTheme} from "@mui/material";

import { CustomCard } from "@src/styles/mui/customComponents";

import { useSelector, useDispatch } from "react-redux";
import { getActiveTheme, selectTheme } from "@src/redux/reducers/themeReducer";



export default function Home() {
  //const [visible,setVisible] =  useState(true);
  //const[currentTheme,setCurrentTheme] = useState("dark");
 
const dispatch = useDispatch();
const currentTheme = useSelector(selectTheme).activeTheme;

useEffect(() => {
    dispatch(getActiveTheme()); // To get theme from Cookie
  }, []);

    const theme = useTheme();


   const movies = [
        {
            name: "Avengers",
            img: "https://wallpaperaccess.com/full/1104056.jpg",
            desc: "Directed by james cameron",
        },
        {
            name : "Terminator",
            img: "https://townsquare.media/site/295/files/2019/10/Terminator-Orion.jpg?w=1200&h=0&zc=1&s=0&a=t&q=8",
            desc: "Directed by Cameron",
        },
        {
            name: "Inception",
            img: "https://images5.alphacoders.com/112/1122037.jpg",
            desc: "Directed by chris nolan",
            
        },
         {
      name: "Jurassic Park",
      img: "https://i.ytimg.com/vi/Rc_i5TKdmhs/maxresdefault.jpg",
      desc: "Directed By Steven Spielberg",
    },
    {
      name: "Superman",
      img: "https://wallpaperaccess.com/full/1996221.jpg",
      desc: "Directed by James Gunn",
    },
    ];
  return (
    
    <>
    <ThemeProvider theme={currentTheme === "dark" ? Darktheme : lighttheme}>
      <CssBaseline/>
      <Head>
        <title>The movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <MyAppBar/>
  
      
      
    {/*<Button onClick={() => setVisible(!visible)}>Toggle</Button>*/}
    <Box height ="25px"/>
       <Box>

      <Container>
            <Grid container spacing={2} direction="row" justifyContent="center">
              {movies ? movies.map((movie) => (
                <Grid size={4}>
                  <CustomCard name={movie.name} image={movie.img} description={movie.desc} />
                </Grid>
              )) : <></>}
            </Grid>
          </Container>
          
    { /*<Box height="200px"/> 
     
      {
        visible ? 
        (<Box sx= {{background :"pink", height :"200px", width : "200px"}}/>
        ) : (
        <></>
      )
        
      }*/}
      
    </Box>
    </ThemeProvider>
      
    </>
  );
}
