//Imports from react
import Head from "next/head";
import { useState } from "react"; //state can change many states in page
import MyAppBar from "@src/components/common/MyAppBar";
import { Box, Button, ThemeProvider } from "@mui/material";

import { theme, Darktheme } from "@src/styles/mui/theme"; 

export default function Home() {
  const [visible,setVisible] =  useState(true);
 

   const movies = [
        {
            name: "Avengers",
            img: "http://www.bing.com/images/search?view=detailV2&ccid=XWqu3U8k&id=CE80BF17293C1FDB646658F3091158D5FC2BF1F8&thid=OIP.XWqu3U8kzfSEbQCoLf-q4wHaHa&mediaurl=https%3a%2f%2fimage.api.playstation.com%2fvulcan%2fap%2frnd%2f202303%2f2318%2fca9f73eaff9ea919bd155d160796afacd98f8e5954c80a4b.png&exph=1024&expw=1024&q=avengers&FORM=IRPRST&ck=648CF3F8CD2BDF5956C9383A049694C2&selectedIndex=0&itb=0",
            desc: "Directed by james cameron",
        },
        {
            name : "Terminator",
            img: "https://www.bing.com/images/search?view=detailV2&ccid=kdNlbAud&id=4B508F83BC96A34FBEA59D2483B3BC6CD1A5CE5E&thid=OIP.kdNlbAud0jA21aLAf48CKQHaKz&mediaurl=https%3a%2f%2fwww.theterminatorfans.com%2fwp-content%2fuploads%2f2015%2f05%2fTerminator-Genisys-US-Poster.jpeg&exph=2758&expw=1891&q=termnator&FORM=IRPRST&ck=D313C6CB5BC00C56E709500E36B4603F&selectedIndex=0&itb=0",
            desc: "Directed by Cameron",
        },
        {
            name: "Inception",
            img: "https://www.bing.com/images/search?view=detailV2&ccid=vnJImFIy&id=34D33593B7A42BB09E493104F8829673D726F69B&thid=OIP.vnJImFIy1GEoBBAjyZ-tfQHaK-&mediaurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.be7248985232d46128041023c99fad7d%3frik%3dm%252fYm13OWgvgEMQ%26riu%3dhttp%253a%252f%252fwww.nolanfans.com%252fimages%252fposters%252finception%252fp4xfull.jpg%26ehk%3dfTBnrxgKiU4dJQxZMWXrFmdjr5dpguBG6osjjkLxxPA%253d%26risl%3d1%26pid%3dImgRaw%26r%3d0&exph=3300&expw=2228&q=inception&FORM=IRPRST&ck=CCCEA35F28B79BCED05834A1F624DF72&selectedIndex=0&itb=0",
            desc: "Directed by abd",
        },
    ];
  return (
    
    <>
    <ThemeProvider theme={ theme }>
      <Head>
        <title>The movie lovers club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <MyAppBar></MyAppBar>
      
      
    <Button onClick={() => setVisible(!visible)}>Toggle</Button>
    <Box>
      <Box height="200px"/> 
      {
        visible ? 
        (<Box sx= {{background :"pink", height :"200px", width : "200px"}}/>
        ) : (
        <></>
      )
        
      }
      
    </Box>
    </ThemeProvider>
      
    </>
  );
}
